config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users, only: [:index, :show, :edit, :update] 
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
validates :title, presence: true
validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about] # top, about の2つのアクションのみ、ログイン無しでもアクセス可能にする
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user) # ログインした直後は、ユーザーの詳細ページに遷移
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def new
    @book = Book.new(book_paarams)
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index, status: :unprocessable_entity
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    book = Book.find(params[:id])
    @user = book.user
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
   
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
   before_action :is_matching_login_user, only: [:edit, :update]
   
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
		if @user.update(user_params)
		  flash[:notice] = "You have updated user successfully."
		redirect_to user_path(@user)
		else
		  render :edit
		end
  end
	
	private

   def user_params
   	   params.require(:user).permit(:name, :introduction, :profile_image)
   end
   
  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
  　<% if @book.errors.any? %>
    　<h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
   　 <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
   　　 <% end %>
    　</ul>
  　<% end %>
      <%= form_with model: @book, method: :patch, local:true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
      
      <div>
</div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <!-- モックのため、固定値や未実装になっている部分があります。アプリ完成前に修正しましょう。 -->
        <table class='table'>
          <tr>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "default-image.jpg" %> 
          </tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th> 
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>  
          </tr>
        </table>　 
        <div class='row'>
          <!-- 編集リンクが未実装 -->
          <%= link_to(edit_user_path(current_user.id), class:  "btn btn-outline-secondary btn-block") do %>
	        	<span class="fas fa-user-cog" aria-hidden="true"></span>
		    <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <div>
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        </div>
        <!-- form_withを用いて新規投稿フォームを作成しましょう。 -->
        <%= form_with model:@book, local:true do |f| %>
          <h6>Title</h6>
          <div class="form-group">
          <%= f.text_field:title, class: "form-control" %>
          </div>
          <h6>Opinion</h6>
          <div class="form-group">
          <%= f.text_area:body, class: "form-control" %>
          </div>
          <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <!-- 投稿した書籍一覧表示を作成しましょう。 -->
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "80x80" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                   <%= book.title %>
                  <% end %>
                </td>
                 <td><%= book.body %></td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>>

app/views/books/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <!-- モックのため、固定値や未実装になっている部分があります。アプリ完成前に修正しましょう。 -->
        <table class='table'>
          <tr>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "default-image.jpg" %> 
          </tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th> 
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>  
          </tr>
        </table>　 
        <div class='row'>
          <!-- 編集リンクが未実装 -->
          <%= link_to(edit_user_path(@book.user.id), class:  "btn btn-outline-secondary btn-block") do %>
	        	<span class="fas fa-user-cog" aria-hidden="true"></span>
		    　<% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <div>
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        </div>
        <!-- form_withを用いて新規投稿フォームを作成しましょう。 -->
        <%= form_with model:@book_new, local:true do |f| %>
          <h6>Title</h6>
          <div class="form-group">
          <%= f.text_field:title, class: "form-control" %>
          </div>
          <h6>Opinion</h6>
          <div class="form-group">
          <%= f.text_area:body, class: "form-control" %>
          </div>
          <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Book detail</h2>
        <!-- 投稿した書籍一覧表示を作成しましょう。 -->
        <table class='table'>
          <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@user) do %>
                    <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', size: "80x80" %><br>
                    <%= @user.name %>
                  <% end %>
                </td>
                <td>
                   <%= link_to book_path(@book) do %> 
                   <%= @book.title %>
                  <% end %>
                </td>
                 <td>
                   <%= @book.body %>
                 </td>
                 <% if @user == current_user %>
          <td>
            <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success"%>
          </td>
          <td>
            <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
          </td>
        <% end %>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>>

app/views/homes/about.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to 
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to 
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>!!
        </h1>
        <p>In 
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
             <!-- ログイン後のHomeリンクは未実装です。自分で調べて実装してみましょう -->
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
               <i class="fas fa-home"></i> Home
              <% end %>
          </li>
          <li>
            <a class="nav-link text-light" href="/users">
              <i class="fas fa-users"></i>Users
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/books">
              <i class="fas fa-book-open"></i>Books
            </a>
          </li>
          <li>
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i>Log out
            </a>
          </li>
          <% else %>
          <li>
            <a class="nav-link text-light" href="/">
              <i class="fas fa-home"></i>Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/home/about">
              <i class="fas fa-link"></i>About
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>Sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %> 
    <%= yield %>
    <%= render 'layouts/footer' %>  
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0">
       <h1>User info</h1>
       <% if @user.errors.any? %>
         <%= @user.errors.count %>errors prohibited this obj from being saved:
         <% @user.errors.full_messages.each do |message| %>
         <%= message %>
         <% end %>
       <% end %>
       <%= form_with model: @user, local: true do |f| %>
        <h6>name</h6>
         <div class="form-group">
           <%= f.text_field :name, class: "form-control" %>
         </div>
  
        <h6>image</h6>
         <div class="form-group">
          <%= f.attachment_field :profile_image, class: "form-control-file" %>
         </div>
        <h6>introduction</h6>
         <div class="form-group">
          <%= f.text_area :introduction, class: "form-control" %>
         </div>
         <div class="form-group">
           <%= f.submit 'Update User' ,class: "btn btn-secondary" %>
        </div>
  <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <!-- モックのため、固定値や未実装になっている部分があります。アプリ完成前に修正しましょう。 -->
        <table class='table'>
          <tr>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "default-image.jpg" %> 
          </tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th> 
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>  
          </tr>
        </table>　 
        <div class='row'>
          <!-- 編集リンクが未実装 -->
          <%= link_to(edit_user_path(current_user.id), class:  "btn btn-outline-secondary btn-block") do %>
	        	<span class="fas fa-user-cog" aria-hidden="true"></span>
		    <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <div>
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        </div>
        <!-- form_withを用いて新規投稿フォームを作成しましょう。 -->
        <%= form_with model:@book, local:true do |f| %>
          <h6>Title</h6>
          <div class="form-group">
          <%= f.text_field:title, class: "form-control" %>
          </div>
          <h6>Opinion</h6>
          <div class="form-group">
          <%= f.text_area:body, class: "form-control" %>
          </div>
          <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <!-- 投稿した書籍一覧表示を作成しましょう。 -->
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
             <% @users.each do |user| %>
              <tr>
                <td>
                <%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "80x80" %>
                </td>
                <td><%= user.name %></td>
                 <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>>

  

app/views/users/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <!-- モックのため、固定値や未実装になっている部分があります。アプリ完成前に修正しましょう。 -->
        <table class='table'>
          <tr>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "default-image.jpg" %> 
          </tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th> 
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>  
          </tr>
        </table>　 
        <div class='row'>
          <!-- 編集リンクが未実装 -->
          <%= link_to(edit_user_path(@user.id), class:  "btn btn-outline-secondary btn-block") do %>
	        	<span class="fas fa-user-cog" aria-hidden="true"></span>
		    　<% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <div>
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        </div>
        <!-- form_withを用いて新規投稿フォームを作成しましょう。 -->
        <%= form_with model:@book, local:true do |f| %>
          <h6>Title</h6>
          <div class="form-group">
          <%= f.text_field:title, class: "form-control" %>
          </div>
          <h6>Opinion</h6>
          <div class="form-group">
          <%= f.text_area:body, class: "form-control" %>
          </div>
          <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <!-- 投稿した書籍一覧表示を作成しましょう。 -->
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "80x80" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                   <%= book.title %>
                  <% end %>
                </td>
                 <td><%= book.body %></td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>>